services:
  db:
    image: postgres:15-alpine
    container_name: botiquin_db
    environment:
      POSTGRES_DB: botiquin_et
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_seguro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: botiquin_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: botiquin_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev

volumes:
  postgres_data:
