# Generated by Django 5.2.16 on 2026-07-23 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('requiere_caducidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('empleo', models.CharField(help_text='Ej: Soldado, Sargento, Teniente...', max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('compania', models.CharField(max_length=50)),
                ('email', models.EmailField(help_text='Correo para simulaciones de avisos', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_caducidad', models.DateField(blank=True, help_text='Dejar en blanco si no caduca (ej: vendas)', null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulosanitario')),
            ],
        ),
        migrations.CreateModel(
            name='RebajeMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baja_total', models.BooleanField(default=False, help_text='Si se marca, representa una baja total.')),
                ('rebaje_deporte', models.BooleanField(default=False)),
                ('rebaje_botas', models.BooleanField(default=False)),
                ('rebaje_instruccion', models.BooleanField(default=False)),
                ('rebaje_orden_cerrado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_revision', models.DateField(help_text='Fecha en la que debe volver al botiquín')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.militar')),
            ],
        ),
    ]
