# Generated by Django 5.2.16 on 2026-08-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='compania',
            field=models.CharField(choices=[('1ºCIA', '1ª Compañía'), ('2ºCIA', '2ª Compañía'), ('3ºCIA', '3ª Compañía'), ('4ºCIA', '4ª Compañía'), ('5ºCIA', '5ª Compañía'), ('PLANA', 'Plana Mayor')], default='1ºCIA', max_length=10),
        ),
    ]
